Add existing role to IRSA module
aws-ia/terraform-aws-eks-blueprints pull request #1234
Opened 2022-12-06 19:46 UTC by nitrocode

### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

### Motivation

- Allows reusing an existing role

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [x] E2E Test successfully complete before merge?

### Additional Notes

```hcl
  # module.pipeline.module.irsa.kubernetes_service_account_v1.irsa[0] will be created
  + resource "kubernetes_service_account_v1" "irsa" {
      + automount_service_account_token = true
      + default_secret_name             = (known after apply)
      + id                              = (known after apply)

      + metadata {
          + annotations      = {
              + "eks.amazonaws.com/role-arn" = "<redacted>"
            }
          + generation       = (known after apply)
          + name             = "<redacted>-sa"
          + namespace        = "default"
          + resource_version = (known after apply)
          + uid              = (known after apply)
        }
    }
```

2022-12-17 00:15 UTC, askulkarni2 commented
@nitrocode please open an issue to describe the problem.

2023-01-17 00:27 UTC, nitrocode commented
@askulkarni2 I created this issue https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1262 on Dec 17 2022.

2023-02-11 01:07 UTC, bryantbiggs requested changes
this still creates an IAM role, even if that IAM role is not used by the service account

2023-03-17 13:25 UTC, bryantbiggs commented
see https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1262#issuecomment-1473840737

2023-03-17 13:25 UTC, closed without merging