chore: Update examples to use `terraform-aws-eks` module where possible
aws-ia/terraform-aws-eks-blueprints pull request #1428
Opened 2023-02-11 01:58 UTC by bryantbiggs

### What does this PR do?

- Update examples to use `terraform-aws-eks` module where possible

### Motivation

- Relates to #1421 

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### Additional Notes

2023-02-11 02:06 UTC, bryantbiggs commented
any examples that have moved (raised to root of `examples/` directory) or have been removed will show as a fail on the CI checks - this is to be expectdd

2023-02-13 15:48 UTC, askulkarni2 approved these changes
LGTM!

2023-02-13 18:13 UTC, Zvikan approved these changes

2023-02-13 20:25 UTC, vara-bonthu requested changes
emr-eks-fargate example can be removed as well from this repo. I have raised a PR to move this pattern to Data on EKS.

2023-02-14 16:13 UTC, vara-bonthu approved these changes

2023-02-14 21:25 UTC, merged