Feat(pattern): Kubecost with AWS CUR Report
aws-ia/terraform-aws-eks-blueprints pull request #1862
Opened 2024-01-20 01:20 UTC by candonov

# Description

### Motivation and Context

- Resolves #927 

### How was this change tested?

- [X] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [X] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

### Additional Notes

2024-01-25 15:19 UTC, rodrigobersa requested changes
Few minor comments!

2024-01-25 15:19 UTC, rodrigobersa commented on patterns/kubecost/README.md
> +```
````suggestion
```
terraform init
terraform apply --auto-approve
```
````

2024-01-25 15:19 UTC, rodrigobersa commented on patterns/kubecost/README.md
> +```
Same here for the default procedure ()

````suggestion
```
cd run-me-in-24h/
terraform destroy --auto-approve
```

```
cd ..
terraform destroy -target="module.eks_blueprints_addon" --var="kubecost_token=<your-kubecost-token>" -auto-approve
terraform destroy -target="module.eks_blueprints_addons" 
terraform destroy -target="module.eks" -auto-approve
terraform destroy -auto-approve
```
````

2024-01-25 15:19 UTC, rodrigobersa commented on patterns/kubecost/main.tf
Can we break down this file in 3-4 files to avoid having a ~400 lines file? We can use the same approach we have [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/privatelink-access).
main.tf (providers, locals)
eks.tf (EKS cluster, cluster VPC, addons)
kubecost.tf (Kubecost related resources)

2024-01-25 15:19 UTC, rodrigobersa commented on patterns/kubecost/main.tf
> +      "${aws_s3_bucket.cur.arn}",
Same here:
```suggestion
      aws_s3_bucket.cur.arn,
```

2024-01-25 15:19 UTC, rodrigobersa commented on patterns/kubecost/main.tf
> +      "${aws_s3_bucket.athena_results.arn}",
Remove the interpolation syntax to pass CI tests.

```suggestion
      aws_s3_bucket.athena_results.arn,
```

2024-01-26 17:01 UTC, candonov commented on patterns/kubecost/main.tf
Most of the patterns have everything in main.tf. My preference is to keep everything in main.tf, even though it is long, the sections are clearly identified.

2024-01-26 21:10 UTC, rodrigobersa approved these changes
Awesome!

2024-01-26 21:10 UTC, merged