Add Ondat
aws-ia/terraform-aws-eks-blueprints pull request #255
Opened 2022-02-14 12:03 UTC by cvlc

### What does this PR do?
This PR provides a Terraform module to install a fully-fledged Ondat cluster using EKS, Helm and using a few Ondat OSS Terraform modules for etcd and storage.

### Motivation
This contribution is aimed to provide an easy path for users to deploy Ondat within AWS with EKS. 

### More

- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [X] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [X] [Yes, I have created another PR for add-ons](https://github.com/aws-samples/ssp-eks-add-ons/pull/11) under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable)
- [X] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

- An Ubuntu for EKS AMI is required for Ondat worker nodes as Amazon Linux and Bottlerocket currently lack the required kernel module `target_core_user`. [A feature request has been raised to resolve this](https://github.com/amazonlinux/amazon-linux-2022/issues/88).
- An external etcd cluster is currently required for Ondat, this is deployed using the MIT-licensed Terraform module [etcd3-terraform](https://github.com/ondat/etcd3-terraform) with the binary [etcd3-bootstrap](https://github.com/ondat/etcd3-bootstrap) used to attach EBS at runtime to persist storage through the EKS node lifecycle.

2022-02-28 21:31 UTC, kcoleman731 commented
@cvlc thanks again for this PR! 

We merged the extensibility guide for partners last week. https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/docs/extensibility.md. As you will see in the doc, the recommendation is for partners to maintain their add-ons in a repo that they own. This allows you to evolve your add-on independent of the core repo.

Please review the guide and let us know if you have any questions.

2022-03-21 17:15 UTC, askulkarni2 commented
Hello @cvlc. Did you have a chance to look at [this](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/255#issuecomment-1054682783) comment? We also recently merged [Tetrate Istio](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/docs/add-ons/tetrate-istio.md) which you can look at a reference example for a partner addon.  Please let us know if you need any additional guidance.

2022-03-31 11:44 UTC, cvlc commented
Thanks all, I've made updates according to the documentation and examples provided!

2022-03-31 14:58 UTC, vara-bonthu commented on modules/kubernetes-addons/main.tf
> +  source            = "github.com/ondat/terraform-eksblueprints-ondat-addon"
Could you please pin this to specific tag 
e.g.,   `version              = "0.0.1"`

2022-04-04 10:48 UTC, cvlc commented
Thanks - I've pinned the version and switched to the Terraform registry as module source. I did try with a combined object variable but I found it easier to debug with multiple - it can get a bit confusing when you're working with a massive object, especially if you mark it sensitive in the state!

2022-04-06 09:52 UTC, cvlc commented
Hi all,
I came across an issue with passing a resource attribute directly through to a list that's iterated on via for_each in v0.0.1, after fixing it I've released v0.0.2.

2022-04-07 17:36 UTC, askulkarni2 requested changes
@cvlc thanks so much for the PR and the updates. One requested change from my side. Here https://github.com/ondat/terraform-eksblueprints-ondat-addon/blob/d1f4dd18315b93ceca554bb6f209f4b6d1c5d64a/main.tf#L12, please pin source to version `ref=v4.0.1` (assuming you have tested with that).

2022-04-08 11:05 UTC, cvlc commented
@askulkarni2 Sure thing, please see https://github.com/ondat/terraform-eksblueprints-ondat-addon/blob/0.0.2/main.tf#L12!

2022-04-12 15:37 UTC, cvlc commented
Hi all,

Now the repo has been renamed I've released a new version and updated all references.

2022-04-13 20:24 UTC, askulkarni2 approved these changes
LGTM!

2022-04-13 21:43 UTC, askulkarni2 commented
Hi @cvlc, thanks for the updates. The code changes look good. However, I am seeing the following when I test the blueprint example from your repo. Can you please check at your end?

```sh
▶ k get pods -n storageos
NAME                                   READY   STATUS             RESTARTS   AGE
ondat-ondat-operator-c8b7d4fd5-nckjz   2/2     Running            0          7m26s
storageos-node-2b8jt                   2/3     CrashLoopBackOff   5          6m56s
storageos-node-ct6s9                   2/3     CrashLoopBackOff   5          6m56s
storageos-node-sfkbj                   2/3     CrashLoopBackOff   5          6m56s
storageos-scheduler-5ddc468b54-dwlgq   1/1     Running            0          7m6s
```

Upon checking the logs for one of the pods, I see the following error..

```
{"endpoints":["https://etcd.us-east-2.i.a.aws001-preprod-dev-etcd.int:2379"],"error":"context deadline exceeded","level":"error","msg":"unable to connect to etcd","store":"etcd","time":"2022-04-13T21:35:27.75302845Z"}
{"error":"failed to instantiate ETCD: context deadline exceeded","level":"error","msg":"failed to initialise store client","time":"2022-04-13T21:35:27.762018823Z"}
{"level":"info","msg":"shutting down","time":"2022-04-13T21:35:27.762108558Z"}
```

2022-04-14 13:19 UTC, cvlc commented
Thanks - I've figured out the issue and will update when it's resolved!

2022-04-14 20:18 UTC, cvlc commented
Hi all, 

The problems are now resolved! Please do try again after a `terraform get -update`. I have updated etcd and Ondat, merged in @askulkarni2's suggestion for adding a Helm provider block and have made some changes to the etcd Terraform logic and EBS bootstrap component to work with the latest AWS and EKS Ubuntu images.

2022-04-16 19:27 UTC, vara-bonthu approved these changes
Thanks @cvlc 👍🏼  LGTM

2022-04-17 11:30 UTC, bryantbiggs approved these changes

2022-04-17 19:05 UTC, merged