Add Permission Boundary Support to AWS Load Balancer Controller
aws-ia/terraform-aws-eks-blueprints pull request #261
Opened 2022-02-15 13:02 UTC by bobdoah

### What does this PR do?

Allow a permissions boundary to be applied to the IRSA IAM role. Additionally, support applying it to the role created by the AWS load balancer controller addon.  

### Motivation

We use a IAM role to provision our Terraform which has permissions boundary attached. That policy must be applied to all IAM roles created by the Terraform. It is used to prevent privilege escalation in keeping with https://aws.amazon.com/premiumsupport/knowledge-center/iam-permission-boundaries/
 

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

I would be happy to add the same functionality to the other addons, as they're adopted by us. I do not have the capacity to test them at the moment.

2022-02-15 15:28 UTC, vara-bonthu commented on modules/kubernetes-addons/aws-load-balancer-controller/README.md
> +<!--- END_TF_DOCS --->
See the above comment

2022-02-15 15:28 UTC, vara-bonthu commented on modules/kubernetes-addons/aws-load-balancer-controller/README.md
> -<!--- END_TF_DOCS --->
This shouldn't be removed

2022-02-15 15:34 UTC, vara-bonthu requested changes
Hi @bobdoah Thanks for your first contribution on our repo 👍🏼 
I understand this is useful feature to control the IAM roles. 

PR Looks good to me. I have one comment on docs that needs addressing

2022-02-15 20:21 UTC, kcoleman731 commented
@bobdoah thank you for the PR! 

To aid in adding support to other add-ons, it probably makes sense to add permission boundary support the [`helm-addon` submodule](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/modules/kubernetes-addons/helm-addon). LBC add-on doesn't leverage the `helm-addon` submodule yet, but our plan is to update all add-ons which deploy helm charts to leverage it in the near future. We could prioritize updating the LBC add-on if you need.

2022-02-16 10:12 UTC, bobdoah commented
Thanks @vara-bonthu, @kcoleman731 for the prompt response.

I have corrected the documentation markers, an oversight on my part. I had thought I had inserted the docs in the correct place.

@kcoleman731 I have added support to the `helm-addon` module as suggested. It didn't look like there were many modules using that, at the moment. It would be great if you could prioritise the LBC change. My intent was to revisit the other modules as I adopted them.

2022-02-16 10:21 UTC, bobdoah commented
Realised I need to add this to the modules using `helm-addon` or they will not work.

2022-02-16 12:51 UTC, vara-bonthu approved these changes
Nice Work on this PR 👍🏼  LGTM!

2022-02-17 09:29 UTC, bobdoah commented
Any chance of getting this merged? Is there something I need to do fix the pr-test action?

2022-02-17 10:05 UTC, merged