feat: Add support for setting `cluster_version` in EKS managed node group sub-module
aws-ia/terraform-aws-eks-blueprints pull request #470
Opened 2022-04-25 22:58 UTC by bryantbiggs

### What does this PR do?
- Add support for setting `cluster_version` in EKS managed node group sub-module
- Remove redundant empty map check on `for_each` loops of `eks-worker.tf`
- Pre-commit hook versions updated to latest (no-op)

### Motivation
- Allows users to specify `version` on EKS managed node group

### More

- [ ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2022-04-25 23:10 UTC, kcoleman731 approved these changes
LGTM

2022-04-26 06:10 UTC, askulkarni2 approved these changes

2022-04-26 06:37 UTC, vara-bonthu requested changes
Thanks @bryantbiggs ! Few changes requested

2022-04-26 06:37 UTC, vara-bonthu commented on eks-worker.tf
> +  cluster_version = var.cluster_version
We already have a `cluster_version` variable in `local.node_group_context`. We just need to leverage that
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/093574f79a50413b961376d9ec0310bda6b514b9/modules/aws-eks-managed-node-groups/variables.tf#L13

2022-04-26 06:37 UTC, vara-bonthu commented on modules/aws-eks-managed-node-groups/main.tf
> +  version              = var.cluster_version
This will become 
```hcl
version              = var.context.eks_cluster_version
```

2022-04-26 06:37 UTC, vara-bonthu commented on modules/aws-eks-managed-node-groups/variables.tf
> +}
We can remove this

2022-04-26 06:37 UTC, vara-bonthu commented on eks-worker.tf
> +  for_each = var.managed_node_groups
Nice!

2022-04-26 20:19 UTC, vara-bonthu approved these changes

2022-04-26 20:35 UTC, merged