External secrets operator
aws-ia/terraform-aws-eks-blueprints pull request #612
Opened 2022-06-08 13:11 UTC by bobdoah

### What does this PR do?

Adds the [External Secrets operator](https://external-secrets.io/v0.5.6/) as an addon

### Motivation

The External Secrets operator integrates external secrets management services with a Kubernetes cluster. It's more flexible than the Secret Store CSI driver. It transparently handles secret rotation, as secrets are kept synchronised. By using Kubernetes secrets, it's easy to map secrets as environment variables. 

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [x] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable) (https://github.com/aws-samples/eks-blueprints-add-ons/pull/50)
- [x] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2022-06-09 17:28 UTC, askulkarni2 requested changes
@bobdoah thank for the PR. Its looking good. While deploying the helm-addon is a good first step, a couple of additional items need to be addressed.

1. Need a non-trivial example preferably showing use of both AWS SSM Parameter Store and Secrets Manager.
2. For these two external stores, we need to provide a way for the platform team persona to define authentication mechanism. This can be done by attaching an IRSA role to the pod. This method is described [here](https://external-secrets.io/v0.5.6/provider-aws-parameter-store/#eks-service-account-credentials). Configuring IRSA in the addon can be optional if customers are using AWS SSM or SM.

2022-06-09 18:39 UTC, bobdoah commented
> @bobdoah thank for the PR. Its looking good. While deploying the helm-addon is a good first step, a couple of additional items need to be addressed.
> 
> 1. Need a non-trivial example preferably showing use of both AWS SSM Parameter Store and Secrets Manager.
> 2. For these two external stores, we need to provide a way for the platform team persona to define authentication mechanism. This can be done by attaching an IRSA role to the pod. This method is described [here](https://external-secrets.io/v0.5.6/provider-aws-parameter-store/#eks-service-account-credentials). Configuring IRSA in the addon can be optional if customers are using AWS SSM or SM.

I do actually have an example, that I used to test this. I extended the `examples/complete-kubernetes-addons`. I would assume though, that you'd prefer a separate example in the `examples` directory, even if it's largely based on the complete add-ons example.

2022-06-10 11:02 UTC, bobdoah commented
Added an example @askulkarni2

2022-06-29 11:25 UTC, bobdoah commented
> @bobdoah apologies for the delay and thank you for your patience. A few minor changes based on the recent `awscli` update and merge confict, otherwise this is looking good to go.

Thanks @askulkarni2. I've applied the requested fixes. I also noticed another example had the same `v1alpha1` reference so I've updated that too. Hopefully this is good to go now.

2022-06-29 21:53 UTC, askulkarni2 reviewed
@bobdoah there's CI failure with [tflint](https://github.com/aws-ia/terraform-aws-eks-blueprints/runs/7110992919?check_suite_focus=true). 

In the example, please add a `aws_kms_key` resource like [this](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/472de7016e97280f7a71be51ecf2b02d0f29a785/examples/secrets-management/csi-secrets-driver/main.tf#L99) and provide it in the `aws_secretmanager_secret` resource like [this](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/472de7016e97280f7a71be51ecf2b02d0f29a785/examples/secrets-management/csi-secrets-driver/main.tf#L105).

2022-06-30 18:02 UTC, askulkarni2 approved these changes
LGTM! Thanks for this awesome PR!

2022-06-30 18:03 UTC, merged

2022-06-30 19:43 UTC, bobdoah commented
> LGTM! Thanks for this awesome PR!

Amazing, thanks for merging!