#659
aws-ia/terraform-aws-eks-blueprints pull request #713
Opened 2022-06-30 11:34 UTC by FernandoMiguel

Signed-off-by: Fernando Miguel <github@FernandoMiguel.net>

### What does this PR do
Fixes: #659

### Motivation

That defaults function was part of the optional attributes experiment, and has been intentionally removed in the next phase of the experiment, which has (as of last week) been de-experimentalized and will be stable in the forthcoming v1.3.0.

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2022-06-30 11:35 UTC, FernandoMiguel commented
```
$ terraform -v
Terraform v1.3.0-alpha20220622
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.20.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/vault v3.7.0
```

2022-06-30 11:37 UTC, bryantbiggs requested changes
this is only possible if we force users to use v1.3 (not yet released) and I suspect that many folks will not be on the latest

2022-06-30 11:51 UTC, FernandoMiguel commented
> this is only possible if we force users to use v1.3 (not yet released) and I suspect that many folks will not be on the latest

it's a shame this have been enabled since it was experimental and not guaranteed to be supported in future releases.
I've pushed another commit removing the `optional` blocks.

Currently that is not breaking anything with our code. 
Not sure about other folks with more complex object structures that depend on validating those map arguments.

@bryantbiggs pls review

2022-07-07 07:26 UTC, FernandoMiguel commented
https://github.com/hashicorp/terraform/releases/tag/v1.3.0-alpha20220706

This is going to be a breaking change..
I am not sure what our upgrade path can be...

2022-08-11 17:42 UTC, askulkarni2 commented
Closing this as duplicate of #754 which will be done in milestone v5.

2022-08-11 17:42 UTC, closed without merging